/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Negocio.NegocioClassificacao;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetomello.ClassificacaoProblema;
import projetomello.Cliente;

/**
 *
 * @author aluno
 */
public class TelaEditarClassificacao extends javax.swing.JFrame {

    ArrayList<ClassificacaoProblema> respostaClassificacao;

    public TelaEditarClassificacao() {
        initComponents();
        ListarClassificacao();
        setLocationRelativeTo(this);
    }

    public void ListarClassificacao() {
        try {
            ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
            NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
            respostaClassificacao = negocioClassificacao.listar(classificacaoProblema);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Descricao"});

            for (ClassificacaoProblema cl : this.respostaClassificacao) {
                modelo.addRow(new Object[]{cl.getNome(), cl.getDescricao()});
            }
            jTableListarClassificacao.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListarCliente = new javax.swing.JTable();
        jButtonSalvarClassificacao = new javax.swing.JButton();
        jTextFieldNomeClassificacao = new javax.swing.JTextField();
        LabelNome1 = new javax.swing.JLabel();
        LabelNome2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListarClassificacao = new javax.swing.JTable();
        jButtonRemover = new javax.swing.JButton();
        LabelNome3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();

        jTableListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "RG", "Nome"
            }
        ));
        jTableListarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarClienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListarClienteMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListarCliente);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar a Classificação do Problema");

        jButtonSalvarClassificacao.setText("Alterar");
        jButtonSalvarClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarClassificacaoActionPerformed(evt);
            }
        });

        LabelNome1.setText("Nome:");

        LabelNome2.setText("Descrição:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jTableListarClassificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição"
            }
        ));
        jTableListarClassificacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarClassificacaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListarClassificacaoMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableListarClassificacao);

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        LabelNome3.setText("Código:");

        jTextFieldCodigo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(LabelNome2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNomeClassificacao))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jButtonSalvarClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelNome3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome1)
                    .addComponent(LabelNome3)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarClassificacao)
                    .addComponent(jButtonRemover))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClassificacaoActionPerformed
        if (jTableListarClassificacao.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Você precisa selecionar um campo na tabela");
            return;
        }

        int index = jTableListarClassificacao.getSelectedRow();
        ClassificacaoProblema classProblema = this.respostaClassificacao.get(index);
        ClassificacaoProblema classificacao = new ClassificacaoProblema();
        classificacao.setNome(jTextFieldNomeClassificacao.getText());
        classificacao.setDescricao(jTextAreaDescricao.getText());
        classificacao.setCodigo(classProblema.getCodigo());
        NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
        try {
            negocioClassificacao.atualizar(classificacao);
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            ListarClassificacao();
            jTextFieldNomeClassificacao.setText("");
            jTextAreaDescricao.setText("");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarClassificacaoActionPerformed

    private void jTableListarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClienteMouseClicked

    }//GEN-LAST:event_jTableListarClienteMouseClicked

    private void jTableListarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClienteMousePressed
        jTableListarCliente.editingCanceled(null);
        jTableListarCliente.editingStopped(null);
    }//GEN-LAST:event_jTableListarClienteMousePressed

    private void jTableListarClassificacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClassificacaoMouseClicked
        MouseEvent e = evt;

        int click = e.getClickCount();
        int index = jTableListarClassificacao.getSelectedRow();

        ClassificacaoProblema classificacao = this.respostaClassificacao.get(index);

        jTextFieldNomeClassificacao.setText(classificacao.getNome());
        jTextAreaDescricao.setText(classificacao.getDescricao());
        jTextFieldCodigo.setText(String.valueOf(classificacao.getCodigo()));

    }//GEN-LAST:event_jTableListarClassificacaoMouseClicked

    private void jTableListarClassificacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClassificacaoMousePressed
        jTableListarClassificacao.editingCanceled(null);
        jTableListarClassificacao.editingStopped(null);
    }//GEN-LAST:event_jTableListarClassificacaoMousePressed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed

            try {
                ClassificacaoProblema classificacao = new ClassificacaoProblema();
                classificacao.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));

                NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
                negocioClassificacao.remover(classificacao);
                JOptionPane.showMessageDialog(null, "O problema foi removido!");
                this.dispose();
                new TelaEditarClassificacao().setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Os dados não coincidem com os dados da tabela! Por favor, selecionar novamente");
                this.dispose();
                new TelaEditarClassificacao().setVisible(true);
            }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarClassificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNome1;
    private javax.swing.JLabel LabelNome2;
    private javax.swing.JLabel LabelNome3;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSalvarClassificacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableListarClassificacao;
    private javax.swing.JTable jTableListarCliente;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeClassificacao;
    // End of variables declaration//GEN-END:variables
}
