/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Negocio.NegocioClassificacao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetomello.ClassificacaoProblema;

/**
 *
 * @author aluno
 */
public class TelaConsultarClassificacao extends javax.swing.JFrame {

    ArrayList<ClassificacaoProblema> respostaClassificacao = new ArrayList<>();

    public void ListarClassificacao() {
        try {
            ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
            NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
            respostaClassificacao = negocioClassificacao.listar(classificacaoProblema);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Descricao"});

            for (ClassificacaoProblema cp : this.respostaClassificacao) {
                modelo.addRow(new Object[]{cp.getNome(), cp.getDescricao()});
            }

            jTableListarClassificacao.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public TelaConsultarClassificacao() {
        initComponents();
        setLocationRelativeTo(this);
        ListarClassificacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListarClassificacao = new javax.swing.JTable();
        jTextFieldNomeClassificacao = new javax.swing.JTextField();
        LabelNome1 = new javax.swing.JLabel();
        jButtonProcurarNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableListarClassificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição"
            }
        ));
        jTableListarClassificacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarClassificacaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListarClassificacaoMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableListarClassificacao);

        LabelNome1.setText("Nome:");

        jButtonProcurarNome.setText("Procurar");
        jButtonProcurarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jButtonProcurarNome)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome1))
                .addGap(18, 18, 18)
                .addComponent(jButtonProcurarNome)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListarClassificacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClassificacaoMouseClicked

    }//GEN-LAST:event_jTableListarClassificacaoMouseClicked

    private void jTableListarClassificacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarClassificacaoMousePressed
        jTableListarClassificacao.editingCanceled(null);
        jTableListarClassificacao.editingStopped(null);
    }//GEN-LAST:event_jTableListarClassificacaoMousePressed

    private void jButtonProcurarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarNomeActionPerformed
        try 
        {
            int index = jTableListarClassificacao.getSelectedRow();
            ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
            classificacaoProblema.setNome(jTextFieldNomeClassificacao.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Descricao"});
            NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
            this.respostaClassificacao = negocioClassificacao.listar(classificacaoProblema);

            for (ClassificacaoProblema cp : this.respostaClassificacao)
            {
                modelo.addRow(new Object[]{cp.getNome(), cp.getDescricao()});
            }

            jTableListarClassificacao.setModel(modelo);           
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonProcurarNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarClassificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNome1;
    private javax.swing.JButton jButtonProcurarNome;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableListarClassificacao;
    private javax.swing.JTextField jTextFieldNomeClassificacao;
    // End of variables declaration//GEN-END:variables
}
