/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Negocio.NegocioClassificacao;
import Negocio.NegocioCliente;
import Negocio.NegocioFuncionario;
import Negocio.NegocioOrdemServico;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetomello.ClassificacaoProblema;
import projetomello.Cliente;
import projetomello.Funcionario;
import projetomello.OrdemServico;

/**
 *
 * @author aluno
 */
public class TelaEditarOrdemServico extends javax.swing.JFrame {

    ArrayList<ClassificacaoProblema> respostaClassificacao = new ArrayList<>();
    ArrayList<Cliente> respostaCliente = new ArrayList<>();
    ArrayList<Funcionario> respostaFuncionario = new ArrayList<>();
    ArrayList<OrdemServico> respostaServico = new ArrayList<>();
    final int SOLUCIONAR = 1;
    final int CANCELAR = 2;

    public TelaEditarOrdemServico() {
        initComponents();
        setLocationRelativeTo(this);
        SimpleDateFormat dataCadastro = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldProcurarData.setText(dataCadastro.format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonClassProblema = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCPFCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodClass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMatriculaFun = new javax.swing.JTextField();
        jTextFieldProcurarCPF = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCPF4 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrdemServico = new javax.swing.JTable();
        jLabelCPF5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelCPF3 = new javax.swing.JLabel();
        jLabelCPF1 = new javax.swing.JLabel();
        jTextFieldProcurarData = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonPesquisarCPF = new javax.swing.JButton();
        jButtonPesquisarMatricula = new javax.swing.JButton();
        jButtonPesquisarCodigo = new javax.swing.JButton();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jRadioButtonFuncionario = new javax.swing.JRadioButton();
        jRadioButtonOrdemServico = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumeroOrdem = new javax.swing.JTextField();
        jButtonSolucionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Ordem de Serviço");

        buttonGroup1.add(jRadioButtonClassProblema);
        jRadioButtonClassProblema.setText("Problema");
        jRadioButtonClassProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClassProblemaActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jTextFieldCPFCliente.setEditable(false);

        jLabel2.setText("Classificação");

        jTextFieldCodClass.setEditable(false);
        jTextFieldCodClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodClassActionPerformed(evt);
            }
        });

        jLabel3.setText("Matrícula");

        jTextFieldMatriculaFun.setEditable(false);
        jTextFieldMatriculaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaFunActionPerformed(evt);
            }
        });

        jTextFieldProcurarCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProcurarCPFKeyTyped(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelCPF.setText("CPF:");

        jLabelCPF4.setText("Matricula do Funcionário:");

        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });

        jTableOrdemServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Codigo do Problema", "Matricula do Funcionario"
            }
        ));
        jTableOrdemServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrdemServicoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableOrdemServicoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOrdemServico);

        jLabelCPF5.setText("Código do Problema");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricao);

        jLabelCPF3.setText("Descrição do Problema:");

        jLabelCPF1.setText("Data de Cadastro:");

        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jButtonPesquisarCPF.setText("Pesquisar");
        jButtonPesquisarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCPFActionPerformed(evt);
            }
        });

        jButtonPesquisarMatricula.setText("Pesquisar");
        jButtonPesquisarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarMatriculaActionPerformed(evt);
            }
        });

        jButtonPesquisarCodigo.setText("Pesquisar");
        jButtonPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCodigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCliente);
        jRadioButtonCliente.setText("Cliente");
        jRadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFuncionario);
        jRadioButtonFuncionario.setText("Funcionario");
        jRadioButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncionarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonOrdemServico);
        jRadioButtonOrdemServico.setText("Ordem de Serviço");
        jRadioButtonOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdemServicoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nº Ordem: ");

        jTextFieldNumeroOrdem.setEnabled(false);

        jButtonSolucionar.setText("Solucionar");
        jButtonSolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolucionarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCPF1)
                                    .addGap(165, 165, 165))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCPF4)
                                    .addComponent(jLabelCPF5)
                                    .addComponent(jLabelCPF)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldMatricula)
                                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonPesquisarMatricula)
                                                    .addComponent(jButtonPesquisarCodigo)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldProcurarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPesquisarCPF))))))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonOrdemServico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButtonCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButtonFuncionario)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButtonClassProblema))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldMatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldCodClass, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabelCPF3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSolucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCPF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProcurarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonCliente)
                            .addComponent(jRadioButtonFuncionario)
                            .addComponent(jRadioButtonClassProblema)
                            .addComponent(jRadioButtonOrdemServico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPF3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonSolucionar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonRemover))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonClassProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClassProblemaActionPerformed
        if (jRadioButtonClassProblema.isSelected()) {
            jButtonRemover.setVisible(false);
            try {
                ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
                NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
                respostaClassificacao = negocioClassificacao.listar(classificacaoProblema);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Código", "Nome", "Descricao"});

                for (ClassificacaoProblema cp : this.respostaClassificacao) {
                    modelo.addRow(new Object[]{cp.getCodigo(), cp.getNome(), cp.getDescricao()});
                }

                jTableOrdemServico.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falta selecinar algum campo (CPF, Matricula, Classificação)");
            }
        }
    }//GEN-LAST:event_jRadioButtonClassProblemaActionPerformed

    private void jTextFieldCodClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodClassActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {

            OrdemServico ordemServico = new OrdemServico();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            jTextFieldProcurarData.setText(formato.format(new Date(System.currentTimeMillis())));
            Date dataCadastro = new java.sql.Date(formato.parse(jTextFieldProcurarData.getText()).getTime());
            ordemServico.setDataCadastro(dataCadastro);
            ordemServico.getClassificacao().setCodigo(Integer.parseInt(jTextFieldCodClass.getText()));
            ordemServico.getCliente().setCpf(jTextFieldCPFCliente.getText());
            ordemServico.getFuncionario().setMatricula(Integer.parseInt(jTextFieldMatriculaFun.getText()));
            ordemServico.setDescricaoProblema(jTextAreaDescricao.getText());
            ordemServico.setNumero(Integer.parseInt(jTextFieldNumeroOrdem.getText()));
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            negocioOrdem.atualizar(ordemServico);
            JOptionPane.showMessageDialog(null, "Ordem de Servico cadastrada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "A Ordem de serviço não esta cadastrada! Tenta selecionar outra Ordem de Serviço previamente cadastrada");
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableOrdemServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrdemServicoMouseClicked
        MouseEvent e = evt;
        int click = e.getClickCount();
        int index = jTableOrdemServico.getSelectedRow();

        if (jRadioButtonOrdemServico.isSelected() == true) {
            OrdemServico ordem = this.respostaServico.get(index);
            jTextFieldNumeroOrdem.setText(String.valueOf(ordem.getNumero()));
        }
        if (jRadioButtonCliente.isSelected()) {
            Cliente cliente = this.respostaCliente.get(index);
            jTextFieldCPFCliente.setText(cliente.getCpf());
        }
        if (jRadioButtonFuncionario.isSelected()) {
            Funcionario funcionario = this.respostaFuncionario.get(index);
            jTextFieldMatriculaFun.setText(String.valueOf(funcionario.getMatricula()));
        }
        if (jRadioButtonClassProblema.isSelected()) {
            ClassificacaoProblema classProblema = this.respostaClassificacao.get(index);
            jTextFieldCodClass.setText(String.valueOf(classProblema.getCodigo()));
        }
    }//GEN-LAST:event_jTableOrdemServicoMouseClicked

    private void jTableOrdemServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrdemServicoMousePressed
        jTableOrdemServico.editingCanceled(null);
        jTableOrdemServico.editingStopped(null);
    }//GEN-LAST:event_jTableOrdemServicoMousePressed

    private void jButtonPesquisarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCPFActionPerformed
        try {
            Cliente clienteNovo = new Cliente();
            clienteNovo.setCpf(jTextFieldProcurarCPF.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});
            NegocioCliente negocioCliente = new NegocioCliente();
            this.respostaCliente = negocioCliente.listar(clienteNovo);

            for (Cliente c : this.respostaCliente) {
                modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
            }
            jTableOrdemServico.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarCPFActionPerformed

    private void jButtonPesquisarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarMatriculaActionPerformed
        try {
            Funcionario funcionario = new Funcionario();
            funcionario.setMatricula(Integer.parseInt(jTextFieldMatricula.getText()));
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});
            NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
            this.respostaFuncionario = negocioFuncionario.listar(funcionario);

            for (Funcionario c : this.respostaFuncionario) {
                modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
            }
            jTableOrdemServico.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarMatriculaActionPerformed

    private void jButtonPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCodigoActionPerformed
        try {
            ClassificacaoProblema classProblema = new ClassificacaoProblema();
            NegocioClassificacao negocioClass = new NegocioClassificacao();
            classProblema.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
            this.respostaClassificacao = negocioClass.listar(classProblema);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Código", "Nome", "Descrição"});

            for (ClassificacaoProblema cl : this.respostaClassificacao) {
                modelo.addRow(new Object[]{cl.getCodigo(), cl.getNome(), cl.getDescricao()});
            }

            jTableOrdemServico.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPesquisarCodigoActionPerformed

    private void jRadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClienteActionPerformed
        if (jRadioButtonCliente.isSelected()) {
            jButtonRemover.setVisible(false);
            try {
                Cliente cliente = new Cliente();
                NegocioCliente negocioCliente = new NegocioCliente();
                respostaCliente = negocioCliente.listar(cliente);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "RG"});

                for (Cliente c : this.respostaCliente) {
                    modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
                }

                jTableOrdemServico.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jRadioButtonClienteActionPerformed

    private void jRadioButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncionarioActionPerformed
        if (jRadioButtonFuncionario.isSelected()) {
            jButtonRemover.setVisible(false);
            try {
                Funcionario funcionario = new Funcionario();
                NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                respostaFuncionario = negocioFuncionario.listar(funcionario);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "RG", "Salario"});

                for (Funcionario f : this.respostaFuncionario) {
                    modelo.addRow(new Object[]{f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
                }

                jTableOrdemServico.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jRadioButtonFuncionarioActionPerformed

    private void jRadioButtonOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdemServicoActionPerformed
        if (jRadioButtonOrdemServico.isSelected() == true) {
            jButtonRemover.setVisible(true);
            try {
                OrdemServico ordemServico = new OrdemServico();
                NegocioOrdemServico negocioOrdemServico = new NegocioOrdemServico();
                respostaServico = negocioOrdemServico.listar(ordemServico);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Cliente", "CPF do Cliente", "Funcionario", "Data de Cadastro", "Problema"});

                for (OrdemServico os : this.respostaServico) {
                    modelo.addRow(new Object[]{os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), os.getDataCadastro(), os.getClassificacao().getNome()});
                }

                jTableOrdemServico.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falta selecinar algum campo (CPF, Matricula, Classificação)");
            }
        }
    }//GEN-LAST:event_jRadioButtonOrdemServicoActionPerformed

    private void jButtonSolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolucionarActionPerformed
        OrdemServico ordemServico = new OrdemServico();
        ordemServico = respostaServico.get(jTableOrdemServico.getSelectedRow());
        new TelaCancelarOuSolucionarOS(ordemServico, this.SOLUCIONAR).setVisible(true);

    }//GEN-LAST:event_jButtonSolucionarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        OrdemServico ordemServico = new OrdemServico();
        ordemServico = respostaServico.get(jTableOrdemServico.getSelectedRow());
        new TelaCancelarOuSolucionarOS(ordemServico, this.CANCELAR).setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        try {
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.setNumero(Integer.parseInt(jTextFieldNumeroOrdem.getText()));

            NegocioOrdemServico negocioOrdemServico = new NegocioOrdemServico();
            negocioOrdemServico.remover(ordemServico);
            JOptionPane.showMessageDialog(null, "A ordem de serviço foi removida!");
            this.dispose();
            new TelaEditarOrdemServico().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falta selecinar algum campo (CPF, Matricula, Classificação)");
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jTextFieldProcurarCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProcurarCPFKeyTyped
        String caracteres = "0123456789.-";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldProcurarCPFKeyTyped

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldMatriculaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaFunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPesquisarCPF;
    private javax.swing.JButton jButtonPesquisarCodigo;
    private javax.swing.JButton jButtonPesquisarMatricula;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSolucionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCPF1;
    private javax.swing.JLabel jLabelCPF3;
    private javax.swing.JLabel jLabelCPF4;
    private javax.swing.JLabel jLabelCPF5;
    private javax.swing.JRadioButton jRadioButtonClassProblema;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonFuncionario;
    private javax.swing.JRadioButton jRadioButtonOrdemServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOrdemServico;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCPFCliente;
    private javax.swing.JTextField jTextFieldCodClass;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldMatriculaFun;
    private javax.swing.JTextField jTextFieldNumeroOrdem;
    private javax.swing.JTextField jTextFieldProcurarCPF;
    private javax.swing.JTextField jTextFieldProcurarData;
    // End of variables declaration//GEN-END:variables
}
