/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Negocio.NegocioClassificacao;
import Negocio.NegocioCliente;
import Negocio.NegocioFuncionario;
import Negocio.NegocioOrdemServico;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetomello.ClassificacaoProblema;
import projetomello.Cliente;
import projetomello.Funcionario;
import projetomello.OrdemServico;

/**
 *
 * @author aluno
 */
public class TelaCadastrarOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarOrdemServico
     */
    ArrayList<Cliente> respostaCliente = new ArrayList<>();
    ArrayList<Funcionario> respostaFuncionario = new ArrayList<>();
    ArrayList<ClassificacaoProblema> respostaClassificacao = new ArrayList<>();

    public void ListaOrdem() {
        if (jRadioButtonCliente.isSelected()) {

        }
    }

    public TelaCadastrarOrdemServico() {
        initComponents();
        setLocationRelativeTo(this);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldProcurarData.setText(formato.format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelCPF3 = new javax.swing.JLabel();
        jLabelCPF1 = new javax.swing.JLabel();
        jTextFieldProcurarData = new javax.swing.JTextField();
        jButtonPesquisarData = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonPesquisarCPF = new javax.swing.JButton();
        jButtonPesquisarMatricula = new javax.swing.JButton();
        jButtonPesquisarCodigo = new javax.swing.JButton();
        jTextFieldProcurarCPF = new javax.swing.JTextField();
        jButtonCadastrarDescricao = new javax.swing.JButton();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCPF4 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelCPF5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jRadioButtonFuncionario = new javax.swing.JRadioButton();
        jRadioButtonClassProblema = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCPFCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodClass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMatriculaFun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordem de Serviço");

        jLabelCPF3.setText("Descrição do Problema:");

        jLabelCPF1.setText("Data de Cadastro:");

        jTextFieldProcurarData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProcurarDataKeyTyped(evt);
            }
        });

        jButtonPesquisarData.setText("Pesquisar");

        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jButtonPesquisarCPF.setText("Pesquisar");

        jButtonPesquisarMatricula.setText("Pesquisar");

        jButtonPesquisarCodigo.setText("Pesquisar");

        jTextFieldProcurarCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProcurarCPFKeyTyped(evt);
            }
        });

        jButtonCadastrarDescricao.setText("Cadastrar");
        jButtonCadastrarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarDescricaoActionPerformed(evt);
            }
        });

        jLabelCPF.setText("CPF:");

        jLabelCPF4.setText("Matricula do Funcionário:");

        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Codigo do Problema", "Matricula do Funcionario"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelCPF5.setText("Código do Problema");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricao);

        buttonGroup1.add(jRadioButtonCliente);
        jRadioButtonCliente.setText("Cliente");
        jRadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFuncionario);
        jRadioButtonFuncionario.setText("Funcionario");
        jRadioButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncionarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonClassProblema);
        jRadioButtonClassProblema.setText("Problema");
        jRadioButtonClassProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClassProblemaActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jTextFieldCPFCliente.setEditable(false);

        jLabel2.setText("Classificação");

        jTextFieldCodClass.setEditable(false);
        jTextFieldCodClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodClassActionPerformed(evt);
            }
        });

        jLabel3.setText("Matrícula");

        jTextFieldMatriculaFun.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCPF1)
                                        .addGap(183, 183, 183))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCPF4)
                                            .addComponent(jLabelCPF5)
                                            .addComponent(jLabelCPF)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextFieldMatricula)
                                                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButtonPesquisarMatricula)
                                                            .addComponent(jButtonPesquisarCodigo)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextFieldProcurarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButtonPesquisarCPF)
                                                            .addComponent(jButtonPesquisarData))))))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonFuncionario)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonClassProblema))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldMatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCodClass, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jButtonCadastrarDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCPF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProcurarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonCliente)
                            .addComponent(jRadioButtonFuncionario)
                            .addComponent(jRadioButtonClassProblema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabelCPF3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrarDescricao)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClienteActionPerformed
        if (jRadioButtonCliente.isSelected()) {
            try {
                Cliente cliente = new Cliente();
                NegocioCliente negocioCliente = new NegocioCliente();
                respostaCliente = negocioCliente.listar(cliente);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "RG"});

                for (Cliente c : this.respostaCliente) {
                    modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
                }

                jTable1.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_jRadioButtonClienteActionPerformed

    private void jRadioButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncionarioActionPerformed
        if (jRadioButtonFuncionario.isSelected()) {
            try {
                Funcionario funcionario = new Funcionario();
                NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                respostaFuncionario = negocioFuncionario.listar(funcionario);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "RG", "Salario"});

                for (Funcionario f : this.respostaFuncionario) {
                    modelo.addRow(new Object[]{f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
                }

                jTable1.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jRadioButtonFuncionarioActionPerformed

    private void jRadioButtonClassProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClassProblemaActionPerformed
        if (jRadioButtonClassProblema.isSelected()) {
            try {
                ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
                NegocioClassificacao negocioClassificacao = new NegocioClassificacao();
                respostaClassificacao = negocioClassificacao.listar(classificacaoProblema);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Código", "Nome", "Descricao"});

                for (ClassificacaoProblema cp : this.respostaClassificacao) {
                    modelo.addRow(new Object[]{cp.getCodigo(), cp.getNome(), cp.getDescricao()});
                }

                jTable1.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jRadioButtonClassProblemaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        MouseEvent e = evt;
        int click = e.getClickCount();
        int index = jTable1.getSelectedRow();

        if (jRadioButtonCliente.isSelected()) {
            Cliente cliente = this.respostaCliente.get(index);
            jTextFieldCPFCliente.setText(cliente.getCpf());
        }
        if (jRadioButtonFuncionario.isSelected()) {
            Funcionario funcionario = this.respostaFuncionario.get(index);
            jTextFieldMatriculaFun.setText(String.valueOf(funcionario.getMatricula()));
        }
        if (jRadioButtonClassProblema.isSelected()) {
            ClassificacaoProblema classProblema = this.respostaClassificacao.get(index);
            jTextFieldCodClass.setText(String.valueOf(classProblema.getCodigo()));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldCodClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodClassActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButtonCadastrarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarDescricaoActionPerformed

        try {

            OrdemServico ordemServico = new OrdemServico();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            jTextFieldProcurarData.setText(formato.format(new Date(System.currentTimeMillis())));
            Date dataCadastro = new java.sql.Date(formato.parse(jTextFieldProcurarData.getText()).getTime());
            ordemServico.setDataCadastro(dataCadastro);
            ordemServico.getClassificacao().setCodigo(Integer.parseInt(jTextFieldCodClass.getText()));
            ordemServico.getCliente().setCpf(jTextFieldCPFCliente.getText());
            ordemServico.getFuncionario().setMatricula(Integer.parseInt(jTextFieldMatriculaFun.getText()));
            ordemServico.setDescricaoProblema(jTextAreaDescricao.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            negocioOrdem.cadastrar(ordemServico);
            JOptionPane.showMessageDialog(null, "Ordem de Servico cadastrada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falta selecinar algum campo (CPF, Matricula, Classificação)");
        }
    }//GEN-LAST:event_jButtonCadastrarDescricaoActionPerformed

    private void jTextFieldProcurarCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProcurarCPFKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldProcurarCPFKeyTyped

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldProcurarDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProcurarDataKeyTyped
        String caracteres = "0123456789/";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldProcurarDataKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCadastrarDescricao;
    private javax.swing.JButton jButtonPesquisarCPF;
    private javax.swing.JButton jButtonPesquisarCodigo;
    private javax.swing.JButton jButtonPesquisarData;
    private javax.swing.JButton jButtonPesquisarMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCPF1;
    private javax.swing.JLabel jLabelCPF3;
    private javax.swing.JLabel jLabelCPF4;
    private javax.swing.JLabel jLabelCPF5;
    private javax.swing.JRadioButton jRadioButtonClassProblema;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCPFCliente;
    private javax.swing.JTextField jTextFieldCodClass;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldMatriculaFun;
    private javax.swing.JTextField jTextFieldProcurarCPF;
    private javax.swing.JTextField jTextFieldProcurarData;
    // End of variables declaration//GEN-END:variables
}
